service: src
frameworkVersion: '2 || 3'
plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

functions:
  getAll:
    handler: src/app/controllers/ClassController.getAll
    events:
      - httpApi:
          path: /
          method: get
  create:
    handler: src/app/controllers/ClassController.create
    events:
      - httpApi:
          path: /controller/create
          method: post
  update:
    handler: src/app/controllers/ClassController.update
    events:
      - httpApi:
          path: /controller/edit/{id}
          method: put
  delete:
    handler: src/app/controllers/ClassController.delete
    events:
      - httpApi:
          path: /controller/delete/{id}
          method: delete
